### ISSUE TITLE
#3 Deploy the website 

### ISSUE THREAD

**Issue by StephMode** [StephMode/personal-website#3]
I want to bring this website live ASAP.

Preferably, I would like to host in a platform other than vercel to learn more about deployement.

Vendors to look out for:

- GitHub
- Vercel

**Tasks**

- [x] Research vendors & make decision
- [x] Deploy on a platform
- [x] Add custom domain to website

**Comment by StephMode** [comment]
Research:

**GitHub pages**: eher für jekyll ausgelegt, funktioniert so ähnlich wie readme, man setzt dezidiertes, speziell benanntes repo auf und da liegt die webite mit production link **drin

**netlify.com**: ähnlich wie vercel ein anderer Anbieter von PaaS/CDN-Plattform. Abstraktionsstufe eines public cloud provider (vercel für AWS), der ein free tier hat.

Weitere Alternativen: digital ocean, sitefinity, cloudways

weitere siehe hier:
https://dev.to/martygo/top-10-vercel-alternatives-in-2023-3mof

**Comment by StephMode** [comment]
Decided for vercel as PaaS and deployed website

**Comment by StephMode** [comment]
Domain purchased and A record successfully set
